### ISSUE TITLE
ecpool does not restart properly

### ISSUE THREAD

**Issue by sngyai** [emqx/ecpool#20]
When I restart supervisor of ecpool and increase its pool size, it cannot be start again, and `gproc_pool` will report an error: 'out_of_range'.
I debug it for a while and found `ecpool_pool` will not call its own `terminate/2` function without trapping exits, thus old `gproc_pool` cannot be shutdown properly(Refer to [Supervisor](https://learnyousomeerlang.com/supervisors#from-bad-to-good#supervisor-concepts), see section `Shutdown`).

Solution: Add following line to [ecpool_pool:init/1](https://github.com/emqx/ecpool/blob/master/src/ecpool_pool.erl#L57)
 ```erl
process_flag(trap_exit, true),
```

**Comment by savonarola** [comment]
This is fixed in https://github.com/emqx/ecpool/commit/cfedc2de0a736dd7aeac10be23a87ed2ff28f087
